#####
name: CycleGAN
port: 6019   #  port parameters for visdom

# 2D
dim: 2
dataroot: '/data/klk/BraTS2019/2D/Train_npy/'    # root directory of the train dataset
testroot: '/data/klk/BraTS2019/2D/Test_npy/'    # root directory of the test dataset
size: [240, 240]

# affine
rotation: 3        # range of rotation if use affine
translation: 0.08    # range of translation if use affine
scaling: 0.08      # range of scaling if use affine

# non affine
non_affine_alpha: 120
gaussian_smoothing: 12

# train
epoch: 0        # starting epoch
n_epochs: 200       # How often do you want to display output images during training
batchSize: 8               # size of the batches
lr: 0.0001                   # initial learning rate
input_nc: 1         
output_nc: 1
loss: "L1" 
cuda: True                
n_cpu: 8
Adv_lamda : 1
Cyc_lamda : 10
Iden_lamda: 5
# output
save_root:  '/home/klk/code/Regist_Evaluator_2D/output/CycleGan/'   # save weight of model