#####
name: Evaluator
port: 6019   #  port parameters for visdom
Noise: True        # Shuffle Remap

# 2D dataset
dim: 2
dataroot: '/data/klk/BraTS2019/2D/Train_npy/'  # root directory of the train dataset
testroot: '/data/klk/BraTS2019/2D/Test_npy/'   # test for image2image translation

# affine
rotation: 3        # range of rotation if use affine
translation: 0.08    # range of translation if use affine
scaling: 0.08      # range of scaling if use affine

# non affine
non_affine_alpha: 120
gaussian_smoothing: 12

# train
size: [240, 240]
epoch: 0      # starting epoch
n_epochs: 200       
n_cpu: 8
batchSize: 8   # size of the batches
lr: 0.0001                   # initial learning rate
input_nc: 2         
output_nc: 1                  
cuda: True
loss: 'L1'

# output root
save_root: './output/IMSE/'   # save weight of model
