#####
name: Registration
port: 6019   #  port parameters for visdom
evaluator_root: './output/IMSE/net_Evaluator.pth'
# 2D
dim: 2
dataroot: '/data/klk/BraTS2019/2D/Train_npy/'    # root directory of the train dataset
testroot: '/data/klk/BraTS2019/2D/Test_npy/'   # root directory of the test dataset
size: [240, 240]
# deformation

# affine
rotation: 3        # range of rotation if use affine
translation: 0.08    # range of translation if use affine
scaling: 0.08      # range of scaling if use affine

# non affine
non_affine_alpha: 120
gaussian_smoothing: 12
# train
epoch: 0        # starting epoch
n_epochs: 100       # How often do you want to display output images during training
batchSize: 8               # size of the batches
lr: 0.0001                   # initial learning rate
input_nc: 2         
output_nc: 1
mode: 'Gen'  #Gen  ，Eva ， Tra       # Generator ,Evaluator ，traditional Multimodal operator
sim: "L1" #   MI  NCC  MIND   # similarity loss

sim_w: 1.0                #Similarity weight
smooth_w: 1               # smooth weight
unet_features: [[16, 32, 32, 32, 32], [32, 32, 32, 32, 16, 16]]
diff: 0   # Differential homeomorphism
cuda: True                
n_cpu: 8

# output
save_root: '/home/klk/code/Regist_Evaluator_2D/output/Reg/'   # save weight of model
