#####
name: Evaluator
port: 6019   #  port parameters for visdom
save_root: '/home/klk/code/IMSE-3D-Pure/output/Eva/'   # save weight of model
epoch: 0        # starting epoch
n_epochs: 200       # How often do you want to display output images during training
batchSize: 1               # size of the batches
dataroot: '/data/klk/BraTS2019/3D/Train_npy/'    # root directory of the train dataset
lr: 0.0001               # initial learning rate
size: [48,128,128]       # W H
depth: 48    # D
input_nc: 2         
output_nc: 1                  
cuda: True                
n_cpu: 2
loss: 'L1'
# affine
rotation: 3        # range of rotation if use affine
translation: 0.08    # range of translation if use affine
scaling: 0.08      # range of scaling if use affine
# non affine
non_affine_alpha: 120
gaussian_smoothing: 12